# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

MM=/usr/bin/gcc
CC=/usr/bin/gcc
CU=/usr/bin/clang
RC=/home/hibiki/.cargo/bin/rustc
MXX=/usr/bin/gcc
CXX=/usr/bin/gcc
AS=/usr/bin/gcc

AR=/usr/bin/ar
RCAR=/home/hibiki/.cargo/bin/rustc
LD=/usr/bin/g++
RCLD=/home/hibiki/.cargo/bin/rustc
SH=/usr/bin/g++
RCSH=/home/hibiki/.cargo/bin/rustc

ospf_LD=/usr/bin/g++
ospf_CXX=/usr/bin/gcc
ospf_CXX=/usr/bin/gcc

ospf_CXXFLAGS=-m64 -g -O0 -std=c++11 -I/usr/include -DDEBUG -DOSPF_VERSION=2 -DTHIS_ROUTER_NAME=\"R0\" -DTHIS_ROUTER_ID=\"1.1.1.1\"
ospf_LDFLAGS=-m64 -L/usr/lib -lpthread

default:  ospf

all:  ospf

.PHONY: default all  ospf

ospf: build/linux/x86_64/debug/ospf
build/linux/x86_64/debug/ospf: build/.objs/ospf/linux/x86_64/debug/src/interface.cpp.o build/.objs/ospf/linux/x86_64/debug/src/lsdb.cpp.o build/.objs/ospf/linux/x86_64/debug/src/main.cpp.o build/.objs/ospf/linux/x86_64/debug/src/neighbor.cpp.o build/.objs/ospf/linux/x86_64/debug/src/packet.cpp.o build/.objs/ospf/linux/x86_64/debug/src/route.cpp.o build/.objs/ospf/linux/x86_64/debug/src/transit.cpp.o
	@echo linking.debug ospf
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(ospf_LD) -o build/linux/x86_64/debug/ospf build/.objs/ospf/linux/x86_64/debug/src/interface.cpp.o build/.objs/ospf/linux/x86_64/debug/src/lsdb.cpp.o build/.objs/ospf/linux/x86_64/debug/src/main.cpp.o build/.objs/ospf/linux/x86_64/debug/src/neighbor.cpp.o build/.objs/ospf/linux/x86_64/debug/src/packet.cpp.o build/.objs/ospf/linux/x86_64/debug/src/route.cpp.o build/.objs/ospf/linux/x86_64/debug/src/transit.cpp.o $(ospf_LDFLAGS)

build/.objs/ospf/linux/x86_64/debug/src/interface.cpp.o: src/interface.cpp
	@echo compiling.debug src/interface.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/interface.cpp.o src/interface.cpp

build/.objs/ospf/linux/x86_64/debug/src/lsdb.cpp.o: src/lsdb.cpp
	@echo compiling.debug src/lsdb.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/lsdb.cpp.o src/lsdb.cpp

build/.objs/ospf/linux/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo compiling.debug src/main.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/main.cpp.o src/main.cpp

build/.objs/ospf/linux/x86_64/debug/src/neighbor.cpp.o: src/neighbor.cpp
	@echo compiling.debug src/neighbor.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/neighbor.cpp.o src/neighbor.cpp

build/.objs/ospf/linux/x86_64/debug/src/packet.cpp.o: src/packet.cpp
	@echo compiling.debug src/packet.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/packet.cpp.o src/packet.cpp

build/.objs/ospf/linux/x86_64/debug/src/route.cpp.o: src/route.cpp
	@echo compiling.debug src/route.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/route.cpp.o src/route.cpp

build/.objs/ospf/linux/x86_64/debug/src/transit.cpp.o: src/transit.cpp
	@echo compiling.debug src/transit.cpp
	@mkdir -p build/.objs/ospf/linux/x86_64/debug/src
	$(VV)$(ospf_CXX) -c $(ospf_CXXFLAGS) -o build/.objs/ospf/linux/x86_64/debug/src/transit.cpp.o src/transit.cpp

clean:  clean_ospf

clean_ospf: 
	@rm -rf build/linux/x86_64/debug/ospf
	@rm -rf build/linux/x86_64/debug/ospf.sym
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/interface.cpp.o
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/lsdb.cpp.o
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/main.cpp.o
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/neighbor.cpp.o
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/packet.cpp.o
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/route.cpp.o
	@rm -rf build/.objs/ospf/linux/x86_64/debug/src/transit.cpp.o

